services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./uploads:/app/uploads
    env_file: ./backend/.env
    ports:
      - 5000:5000
  db:
    image: postgres
    ports:
      - 5433:5432 # local:container
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   # ports:
  #   #  - 3000:3000 # local:container
  #   volumes:
  #     - ./frontend/src:/app/src
  nginx:
    image: nginx
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
