services:
  backend:
    build: 
      context: ./backend
      target: dev
    ports:
      - 5000:5000 # local:container
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5433:5432 # local:container
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  # # uncomment the lines bellow to activate the dockerized frontend for dev
  # frontend:
  #   build: 
  #     context: ./frontend
  #     target: dev
  #   ports:
  #     - 3001:3000 # local:container
  #   volumes:
  #     - ./frontend/src:/app/src

