services:
  backend:
    build: ./backend
    ports:
      - 5000:5000 # local:container
    volumes:
      - ./backend/src:/app/src
      - ./uploads:/app/uploads
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5433:5432 # local:container
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   ports:
  #     - 3001:3000 # local:container
  #   volumes:
  #     - ./frontend/src:/app/src

