services:
  backend:
    build: ./backend
    # ports:
    #  - 5000:5000 # local:container
    volumes:
      - ./backend/src:/app/src
      - ./uploads:/app/uploads
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5433:5432 # local:container
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  frontend:
    build: ./frontend
    command: npm run dev
    # ports:
    #  - 3000:3000 # local:container
    volumes:
      - ./frontend/src:/app/src
  nginx:
    stop_grace_period: 0s
    image: nginx:1.21.3
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs:/var/log/nginx
