CREATE TABLE Category (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
);

CREATE TABLE Ad (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  owner VARCHAR(255) NOT NULL
);

INSERT INTO Ad (title) VALUES ("Super bike"), ("Super car");

SELECT * FROM Ad;

DELETE FROM Ad WHERE id=1;