### Tags - createOne
POST http://localhost:5000/tags
content-type: application/json

{
  "name": "Couleur"
}

### Categories - createOne
POST http://localhost:5000/categories
content-type: application/json

{
  "name": "Second category"
}

### Categories - patchOne
PATCH  http://localhost:5000/categories/1
content-type: application/json

{
  "name": "Updated category"
}

### Categories - getOne
GET http://localhost:5000/categories/1

### Categories - getOne
GET http://localhost:5000/categories/1/ads

### Ads - getAll
GET http://localhost:5000/ads

### Ads - getAll (with filter)
GET http://localhost:5000/ads?categoryIn=2,1&orderByTitle=DESC

### Ads - getOne
GET http://localhost:5000/ads/5

### Ads - createOne
POST http://localhost:5000/ads
content-type: application/json

{
  "title": "Petits gateaux",
  "description": null,
  "price": 100,
  "imgUrl": "https://cdn.pixabay.com/photo/2023/08/26/14/19/cupcake-8215179_1280.jpg",
  "category": { "id": 12 },
  "tags": []
}

### Ads - deleteOne

DELETE http://localhost:5000/ads/1

### Ads - patchOne
PATCH http://localhost:5000/ads/4
content-type: application/json

{
  "title": "Fusée",
  "category": { "id": 2 }
}