name: Backend

on:
  push:

jobs:
  has-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checking for folder changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
  test:
    needs: has-changes
    runs-on: ubuntu-latest
    steps:
      - name: Skip tests
        if: needs.check.outputs.has-changes == 'false'
        run: exit 0;
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto backend and run tests
        run: cd backend && npm i && npm test
  docker:
    needs: test
    if: github.ref == 'refs/heads/master' && needs.check.outputs.has-changes == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO_BACKEND }}:latest, ${{ secrets.DOCKERHUB_REPO_BACKEND }}:${{ github.sha }}
